version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./WebApplication1
      dockerfile: GestionTaller-Back/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=GestionTallerDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - gestion-taller-network

  # Frontend Angular service
  frontend:
    build:
      context: ./GestionTaller-Front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - gestion-taller-network

  # Database service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - gestion-taller-network

networks:
  gestion-taller-network:
    driver: bridge

volumes:
  sqlserver-data: